("PORTBLMP.DGO"
  ("target-turret-shot.o"
   "target-port-turret.o" ;; added - custom code to handle the turret for this mission
   "port-blimp.o"
   "jak-turret+0-ag.go"
   "torn-turret+0-ag.go"
   "torn-highres-ag.go"
   "drill-turret-ext-ag.go"
   "port-metal-head-boat-ag.go"
   "tpage-2934.go"
   "tpage-2935.go"
   "tpage-2967.go"
   "tpage-3071.go"
   "tpage-3130.go"
   "portblmp.go"
  ))